{"level":"error","message":"Metadata validation failed for module \"easy-target\": The file \"main.js\" included by module easy-target does not exist","stack":"Error: Metadata validation failed for module \"easy-target\": The file \"main.js\" included by module easy-target does not exist\n    at PackageAssetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:1457)\n    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1010:40\n    at Array.map (<anonymous>)\n    at SetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1010:18)\n    at SetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1090:26)\n    at Module._initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:216:27)\n    at Module._initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:3231)\n    at new DataModel (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:63:10)\n    at new BasePackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/packages/base-package.mjs:213:5)\n    at new ServerPackageMixin (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:1680)","timestamp":"2024-06-01 15:27:32"}
{"level":"error","message":"Metadata validation failed for module \"simply-portraits\": The file \"main.js\" included by module simply-portraits does not exist","stack":"Error: Metadata validation failed for module \"simply-portraits\": The file \"main.js\" included by module simply-portraits does not exist\n    at PackageAssetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:1457)\n    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1010:40\n    at Array.map (<anonymous>)\n    at SetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1010:18)\n    at SetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1090:26)\n    at Module._initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:216:27)\n    at Module._initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:3231)\n    at new DataModel (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:63:10)\n    at new BasePackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/packages/base-package.mjs:213:5)\n    at new ServerPackageMixin (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:1680)","timestamp":"2024-06-01 15:27:32"}
{"code":"ECOMPROMISED","errno":-4058,"level":"error","message":"ENOENT: no such file or directory, stat 'C:\\Users\\JoshuaWasDead\\YandexDisk\\PC ODIUM-DESKTOP\\FoundryVTT\\Config\\options.json.lock'","path":"C:\\Users\\JoshuaWasDead\\YandexDisk\\PC ODIUM-DESKTOP\\FoundryVTT\\Config\\options.json.lock","stack":"Error: ENOENT: no such file or directory, stat 'C:\\Users\\JoshuaWasDead\\YandexDisk\\PC ODIUM-DESKTOP\\FoundryVTT\\Config\\options.json.lock'","syscall":"stat","timestamp":"2024-06-01 15:28:34"}
{"level":"error","message":"Metadata validation failed for module \"easy-target\": The file \"main.js\" included by module easy-target does not exist","stack":"Error: Metadata validation failed for module \"easy-target\": The file \"main.js\" included by module easy-target does not exist\n    at PackageAssetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:1457)\n    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1010:40\n    at Array.map (<anonymous>)\n    at SetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1010:18)\n    at SetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1090:26)\n    at Module._initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:216:27)\n    at Module._initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:3231)\n    at new DataModel (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:63:10)\n    at new BasePackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/packages/base-package.mjs:213:5)\n    at new ServerPackageMixin (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:1680)","timestamp":"2024-06-01 15:28:42"}
{"level":"error","message":"Metadata validation failed for module \"simply-portraits\": The file \"main.js\" included by module simply-portraits does not exist","stack":"Error: Metadata validation failed for module \"simply-portraits\": The file \"main.js\" included by module simply-portraits does not exist\n    at PackageAssetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:1457)\n    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1010:40\n    at Array.map (<anonymous>)\n    at SetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1010:18)\n    at SetField.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:1090:26)\n    at Module._initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:216:27)\n    at Module._initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:3231)\n    at new DataModel (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:63:10)\n    at new BasePackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/packages/base-package.mjs:213:5)\n    at new ServerPackageMixin (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:1680)","timestamp":"2024-06-01 15:28:42"}
{"code":"ECOMPROMISED","errno":-4058,"level":"error","message":"ENOENT: no such file or directory, stat 'C:\\Users\\JoshuaWasDead\\YandexDisk\\PC ODIUM-DESKTOP\\FoundryVTT\\Config\\options.json.lock'","path":"C:\\Users\\JoshuaWasDead\\YandexDisk\\PC ODIUM-DESKTOP\\FoundryVTT\\Config\\options.json.lock","stack":"Error: ENOENT: no such file or directory, stat 'C:\\Users\\JoshuaWasDead\\YandexDisk\\PC ODIUM-DESKTOP\\FoundryVTT\\Config\\options.json.lock'","syscall":"stat","timestamp":"2024-06-01 15:29:24"}
{"level":"error","message":"The requested data path parent directory \"C:/Users/JoshuaWasDead/YandexDisk/PC ODIUM-DESKTOP\" does not exist.","timestamp":"2024-06-01 15:30:11"}
{"level":"error","message":"Software license verification failed. Please confirm your Foundry Virtual Tabletop software license","timestamp":"2024-06-01 15:30:11"}
{"level":"error","message":"Error loading module \"C:\\Users\\JoshuaWasDead\\AppData\\Local\\FoundryVTT\\Data\\modules\\JB2A_DnD5e\\module.json\": ENOENT: no such file or directory, open 'C:\\Users\\JoshuaWasDead\\AppData\\Local\\FoundryVTT\\Data\\modules\\JB2A_DnD5e\\module.json'","stack":"Error: Error loading module \"C:\\Users\\JoshuaWasDead\\AppData\\Local\\FoundryVTT\\Data\\modules\\JB2A_DnD5e\\module.json\": ENOENT: no such file or directory, open 'C:\\Users\\JoshuaWasDead\\AppData\\Local\\FoundryVTT\\Data\\modules\\JB2A_DnD5e\\module.json'\n    at Module.fromManifestPath (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:4837)\n    at Module._addInstalledPackageToCache (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:8961)\n    at Module.install (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7619)\n    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3657","timestamp":"2024-06-01 15:41:21"}
{"level":"error","message":"Cannot read properties of null (reading 'protected')","stack":"TypeError: Cannot read properties of null (reading 'protected')\n    at Module._checkInstallForSidegrade (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7776)\n    at Module.install (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7693)\n    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3657","timestamp":"2024-06-01 15:41:21"}
{"code":"ENOENT","errno":-4058,"level":"error","message":"ENOENT: no such file or directory, unlink 'C:\\Users\\JoshuaWasDead\\AppData\\Local\\FoundryVTT\\Data\\modules\\JB2A_DnD5e.zip'","path":"C:\\Users\\JoshuaWasDead\\AppData\\Local\\FoundryVTT\\Data\\modules\\JB2A_DnD5e.zip","stack":"Error: ENOENT: no such file or directory, unlink 'C:\\Users\\JoshuaWasDead\\AppData\\Local\\FoundryVTT\\Data\\modules\\JB2A_DnD5e.zip'\n    at Object.unlinkSync (node:fs:1780:3)\n    at PackageInstaller.install (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/installer.mjs:1:1918)\n    at async #s (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:8650)\n    at async Module.install (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7532)\n    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3657","syscall":"unlink","timestamp":"2024-06-01 15:41:32"}
{"level":"error","message":"User Party lacks permission to create Setting [n3W0EuOCQeU5BqEA]","stack":"Error: User Party lacks permission to create Setting [n3W0EuOCQeU5BqEA]\n    at ServerDatabaseBackend._createDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:2776)\n    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)","timestamp":"2024-06-01 16:27:13"}
{"level":"error","message":"You may not modify the pf2e.pathfinder-bestiary Compendium which is currently locked.","stack":"Error: You may not modify the pf2e.pathfinder-bestiary Compendium which is currently locked.\n    at #e (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-compendium.mjs:1:1700)\n    at Actor.canUserModify (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/document.mjs:295:44)\n    at ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4021)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)","timestamp":"2024-06-01 18:19:05"}
{"level":"error","message":"Software license verification failed. Please confirm your Foundry Virtual Tabletop software license","timestamp":"2024-06-01 18:54:51"}
{"level":"error","message":"Software license verification failed. Please confirm your Foundry Virtual Tabletop software license","timestamp":"2024-06-09 09:58:28"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"actors\": Database is not open","stack":"Error: Failed to connect to database \"actors\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"cards\": Database is not open","stack":"Error: Failed to connect to database \"cards\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"messages\": Database is not open","stack":"Error: Failed to connect to database \"messages\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"combats\": Database is not open","stack":"Error: Failed to connect to database \"combats\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"drawings\": Database is not open","stack":"Error: Failed to connect to database \"drawings\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"fog\": Database is not open","stack":"Error: Failed to connect to database \"fog\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"folders\": Database is not open","stack":"Error: Failed to connect to database \"folders\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"items\": Database is not open","stack":"Error: Failed to connect to database \"items\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"journal\": Database is not open","stack":"Error: Failed to connect to database \"journal\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"macros\": Database is not open","stack":"Error: Failed to connect to database \"macros\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"playlists\": Database is not open","stack":"Error: Failed to connect to database \"playlists\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"tables\": Database is not open","stack":"Error: Failed to connect to database \"tables\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"scenes\": Database is not open","stack":"Error: Failed to connect to database \"scenes\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:42"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"settings\": Database is not open","stack":"Error: Failed to connect to database \"settings\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"users\": Database is not open","stack":"Error: Failed to connect to database \"users\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.abomination-vaults-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.abomination-vaults-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.age-of-ashes-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.age-of-ashes-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.agents-of-edgewatch-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.agents-of-edgewatch-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.book-of-the-dead-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.book-of-the-dead-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.blood-lords-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.blood-lords-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.blog-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.blog-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.extinction-curse-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.extinction-curse-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.fall-of-plaguestone-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.fall-of-plaguestone-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.fists-of-the-ruby-phoenix-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.fists-of-the-ruby-phoenix-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.hazards\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.hazards\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.howl-of-the-wild-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.howl-of-the-wild-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.gatewalkers-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.gatewalkers-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.lost-omens-impossible-lands-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.lost-omens-impossible-lands-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.lost-omens-mwangi-expanse-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.lost-omens-mwangi-expanse-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.lost-omens-highhelm-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.lost-omens-highhelm-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.lost-omens-monsters-of-myth-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.lost-omens-monsters-of-myth-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.lost-omens-tian-xia-world-guide\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.lost-omens-tian-xia-world-guide\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.lost-omens-travel-guide-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.lost-omens-travel-guide-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.malevolence-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.malevolence-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.menace-under-otari-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.menace-under-otari-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.npc-gallery\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.npc-gallery\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.one-shot-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.one-shot-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.outlaws-of-alkenstar-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.outlaws-of-alkenstar-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.kingmaker-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.kingmaker-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pathfinder-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pathfinder-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pathfinder-bestiary-2\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pathfinder-bestiary-2\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pathfinder-bestiary-3\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pathfinder-bestiary-3\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pathfinder-monster-core\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pathfinder-monster-core\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pathfinder-dark-archive\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pathfinder-dark-archive\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pfs-introductions-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pfs-introductions-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pfs-season-1-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pfs-season-1-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pfs-season-2-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pfs-season-2-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pfs-season-3-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pfs-season-3-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:43"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pfs-season-4-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pfs-season-4-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pfs-season-5-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pfs-season-5-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.quest-for-the-frozen-flame-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.quest-for-the-frozen-flame-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.rusthenge-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.rusthenge-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.season-of-ghosts-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.season-of-ghosts-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.seven-dooms-for-sandpoint-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.seven-dooms-for-sandpoint-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.shadows-at-sundown-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.shadows-at-sundown-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.sky-kings-tomb-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.sky-kings-tomb-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.strength-of-thousands-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.strength-of-thousands-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.the-enmity-cycle-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.the-enmity-cycle-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.the-slithering-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.the-slithering-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.troubles-in-otari-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.troubles-in-otari-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.night-of-the-gray-death-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.night-of-the-gray-death-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.crown-of-the-kobold-king-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.crown-of-the-kobold-king-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.stolen-fate-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.stolen-fate-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.rage-of-elements-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.rage-of-elements-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.wardens-of-wildwood-bestiary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.wardens-of-wildwood-bestiary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.vehicles\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.vehicles\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.actionspf2e\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.actionspf2e\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.ancestries\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.ancestries\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.ancestryfeatures\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.ancestryfeatures\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.backgrounds\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.backgrounds\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.classes\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.classes\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.classfeatures\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.classfeatures\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.familiar-abilities\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.familiar-abilities\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.feats-srd\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.feats-srd\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.heritages\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.heritages\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.spells-srd\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.spells-srd\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.bestiary-effects\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.bestiary-effects\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.boons-and-curses\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.boons-and-curses\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.conditionitems\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.conditionitems\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.campaign-effects\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.campaign-effects\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.equipment-effects\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.equipment-effects\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.other-effects\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.other-effects\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.feat-effects\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.feat-effects\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pathfinder-society-boons\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pathfinder-society-boons\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.spell-effects\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.spell-effects\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.equipment-srd\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.equipment-srd\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.deities\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.deities\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.iconics\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.iconics\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.paizo-pregens\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.paizo-pregens\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.rollable-tables\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.rollable-tables\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.criticaldeck\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.criticaldeck\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.journals\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.journals\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.gmg-srd\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.gmg-srd\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.action-macros\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.action-macros\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.pf2e-macros\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.pf2e-macros\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.bestiary-ability-glossary-srd\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.bestiary-ability-glossary-srd\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.bestiary-family-ability-glossary\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.bestiary-family-ability-glossary\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.adventure-specific-actions\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.adventure-specific-actions\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e.kingmaker-features\": Database is not open","stack":"Error: Failed to connect to database \"pf2e.kingmaker-features\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"fxmaster.fxmaster\": Database is not open","stack":"Error: Failed to connect to database \"fxmaster.fxmaster\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"JB2A_DnD5e.jb2a-sequencer\": Database is not open","stack":"Error: Failed to connect to database \"JB2A_DnD5e.jb2a-sequencer\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"monks-active-tiles.active-tile-macros\": Database is not open","stack":"Error: Failed to connect to database \"monks-active-tiles.active-tile-macros\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e-jb2a-macros.Macros\": Database is not open","stack":"Error: Failed to connect to database \"pf2e-jb2a-macros.Macros\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e-jb2a-macros.Actors\": Database is not open","stack":"Error: Failed to connect to database \"pf2e-jb2a-macros.Actors\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e-jb2a-macros.Actions\": Database is not open","stack":"Error: Failed to connect to database \"pf2e-jb2a-macros.Actions\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"pf2e-reaction.reaction-effects\": Database is not open","stack":"Error: Failed to connect to database \"pf2e-reaction.reaction-effects\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"cause":{"code":"LEVEL_IO_ERROR"},"code":"LEVEL_DATABASE_NOT_OPEN","level":"error","message":"Failed to connect to database \"troubles-in-otari-remade-maps.troubles-in-otari-maps-remake-by-narchy\": Database is not open","stack":"Error: Failed to connect to database \"troubles-in-otari-remade-maps.troubles-in-otari-maps-remake-by-narchy\": Database is not open\n    at maybeOpened (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:133:18)\n    at C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:160:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2024-06-09 09:58:44"}
{"level":"error","message":"Database is not open","stack":"Error: Database is not open\n    at maybeError (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:806:27)\n    at LevelDatabase.getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:345:9)\n    at SublevelDatabase._getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\lib\\abstract-sublevel.js:137:21)\n    at SublevelDatabase.getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:383:10)\n    at FogExploration.getMany (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-document.mjs:1:4744)\n    at ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:3693)\n    at ServerDatabaseBackend.update (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/backend.mjs:133:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)","timestamp":"2024-06-12 14:07:43"}
{"level":"error","message":"Database is not open","stack":"Error: Database is not open\n    at maybeError (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:806:27)\n    at LevelDatabase.getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:345:9)\n    at SublevelDatabase._getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\lib\\abstract-sublevel.js:137:21)\n    at SublevelDatabase.getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:383:10)\n    at FogExploration.getMany (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-document.mjs:1:4744)\n    at ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:3693)\n    at ServerDatabaseBackend.update (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/backend.mjs:133:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)","timestamp":"2024-06-12 14:11:32"}
{"level":"error","message":"Database is not open","stack":"Error: Database is not open\n    at maybeError (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:806:27)\n    at LevelDatabase.getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:345:9)\n    at SublevelDatabase._getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\lib\\abstract-sublevel.js:137:21)\n    at SublevelDatabase.getMany (C:\\Program Files\\Foundry Virtual Tabletop\\resources\\app\\node_modules\\abstract-level\\abstract-level.js:383:10)\n    at FogExploration.getMany (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-document.mjs:1:4744)\n    at ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:3693)\n    at ServerDatabaseBackend.update (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/backend.mjs:133:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)","timestamp":"2024-06-12 14:32:53"}
